### ISSUE TITLE
A couple of ways to improve the script

### ISSUE THREAD

**Issue by yanf3** [CommanderCRM/SampleFinder#1]
I just tried this and it seems to download the full resolution video with yt-dlp. I think it would be better if it just downloaded the audio, as it would save data and time.
Also, it would be nice if it would convert the video to mp3 while the next video is downloading. It would speed things up a lot (especially for longer videos), but it might be tricky to do.
Thanks for reading

**Comment by CommanderCRM** [comment]
It never downloaded the video itself, as "-x" flag or now "bestaudio" format downloads audio-only .webm. Then the conversion to .mp3 is made. You can try opening .webm using media player - it won't show any video. 

As per speeding things up, it seems like the best possible option in yt-dlp for now is "-N" or its JSON analog "concurrent_fragment_downloads", which speeds up downloads, but sadly does nothing with postprocessing etc.
